name: gallery
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true


  assets:
    - assets/imgs/img1.jpg

    - assets/imgs/img2.jpg

    - assets/imgs/img3.jpg

    - assets/imgs/img4.jpg

    - assets/imgs/img5.jpeg

    - assets/imgs/img6.jpg

    - assets/imgs/img7.jpg

    - assets/imgs/img8.jpg

    - assets/imgs/img9.jpg

    - assets/imgs/img10.jpg


